GLOBALS = globals()
PROJECTNAME = "listen"

HAS_CONTAINER_EVENTS = False

MEMBERSHIP_DENIED = 0
MEMBERSHIP_DEFERRED = 10
MEMBERSHIP_ALLOWED = 20
MEMBERSHIP_PIN_MISMATCH = 30
MEMBERSHIP_ERROR = 40

POST_DENIED = 0
POST_DEFERRED = 10
POST_ALLOWED = 20
POST_ERROR = 40

MODERATION_SUCCESSFUL = 50
MODERATION_FAILED = 60
